# Generated by Django 3.2.13 on 2023-01-30 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_list', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(max_length=200, null=True, upload_to='store_db')),
                ('thorn', models.CharField(max_length=6, null=True)),
                ('code', models.CharField(max_length=20, null=True, unique=True)),
                ('quality', models.CharField(default=0, max_length=50, null=True)),
                ('rest', models.CharField(default=0, max_length=5)),
                ('model', models.CharField(max_length=50, null=True)),
                ('marka', models.CharField(max_length=30, null=True)),
                ('color_disk', models.CharField(max_length=30, null=True)),
                ('price_rozn', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('type_list', models.CharField(max_length=200, null=True)),
                ('wrh_list', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
