# Generated by Django 3.2.13 on 2023-02-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230205_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Код товара:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_disk',
            field=models.CharField(max_length=30, null=True, verbose_name='Цвет диска'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='store_db', verbose_name='Фото:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marka',
            field=models.CharField(max_length=30, null=True, verbose_name='Марка товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=50, null=True, verbose_name='Модель товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Основные параметры:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Цена закупа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_rozn',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(default=0, max_length=50, null=True, verbose_name='Качество: 0-Новые:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rest',
            field=models.CharField(default=0, max_length=5, verbose_name='Количество на складе:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season_list',
            field=models.CharField(max_length=30, null=True, verbose_name='Сезон:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thorn',
            field=models.CharField(max_length=6, null=True, verbose_name='Шипы есть нет:'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_list',
            field=models.CharField(max_length=200, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wrh_list',
            field=models.CharField(max_length=20, null=True, verbose_name='Склад'),
        ),
    ]
